const teams = [
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Atlanta",
      "altCityName":"Atlanta",
      "fullName":"Atlanta Hawks",
      "tricode":"ATL",
      "teamId":"1610612737",
      "nickname":"Hawks",
      "urlName":"hawks",
      "confName":"East",
      "divName":"Southeast"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Boston",
      "altCityName":"Boston",
      "fullName":"Boston Celtics",
      "tricode":"BOS",
      "teamId":"1610612738",
      "nickname":"Celtics",
      "urlName":"celtics",
      "confName":"East",
      "divName":"Atlantic"
   },
   {
      "isNBAFranchise":false,
      "isAllStar":false,
      "city":"Brisbane",
      "altCityName":"Brisbane",
      "fullName":"Brisbane Bullets",
      "tricode":"BNE",
      "teamId":"15017",
      "nickname":"Bullets",
      "urlName":"bullets",
      "confName":"Intl",
      "divName":""
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Brooklyn",
      "altCityName":"Brooklyn",
      "fullName":"Brooklyn Nets",
      "tricode":"BKN",
      "teamId":"1610612751",
      "nickname":"Nets",
      "urlName":"nets",
      "confName":"East",
      "divName":"Atlantic"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Charlotte",
      "altCityName":"Charlotte",
      "fullName":"Charlotte Hornets",
      "tricode":"CHA",
      "teamId":"1610612766",
      "nickname":"Hornets",
      "urlName":"hornets",
      "confName":"East",
      "divName":"Southeast"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Chicago",
      "altCityName":"Chicago",
      "fullName":"Chicago Bulls",
      "tricode":"CHI",
      "teamId":"1610612741",
      "nickname":"Bulls",
      "urlName":"bulls",
      "confName":"East",
      "divName":"Central"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Cleveland",
      "altCityName":"Cleveland",
      "fullName":"Cleveland Cavaliers",
      "tricode":"CLE",
      "teamId":"1610612739",
      "nickname":"Cavaliers",
      "urlName":"cavaliers",
      "confName":"East",
      "divName":"Central"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Dallas",
      "altCityName":"Dallas",
      "fullName":"Dallas Mavericks",
      "tricode":"DAL",
      "teamId":"1610612742",
      "nickname":"Mavericks",
      "urlName":"mavericks",
      "confName":"West",
      "divName":"Southwest"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Denver",
      "altCityName":"Denver",
      "fullName":"Denver Nuggets",
      "tricode":"DEN",
      "teamId":"1610612743",
      "nickname":"Nuggets",
      "urlName":"nuggets",
      "confName":"West",
      "divName":"Northwest"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Detroit",
      "altCityName":"Detroit",
      "fullName":"Detroit Pistons",
      "tricode":"DET",
      "teamId":"1610612765",
      "nickname":"Pistons",
      "urlName":"pistons",
      "confName":"East",
      "divName":"Central"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Golden State",
      "altCityName":"Golden State",
      "fullName":"Golden State Warriors",
      "tricode":"GSW",
      "teamId":"1610612744",
      "nickname":"Warriors",
      "urlName":"warriors",
      "confName":"West",
      "divName":"Pacific"
   },
   {
      "isNBAFranchise":false,
      "isAllStar":false,
      "city":"Guangzhou",
      "altCityName":"Guangzhou",
      "fullName":"Guangzhou Long-Lions",
      "tricode":"GUA",
      "teamId":"15018",
      "nickname":"Long-Lions",
      "urlName":"long-lions",
      "confName":"Intl",
      "divName":""
   },
   {
      "isNBAFranchise":false,
      "isAllStar":false,
      "city":"Haifa",
      "altCityName":"Haifa",
      "fullName":"Maccabi Haifa",
      "tricode":"MAC",
      "teamId":"93",
      "nickname":"Maccabi Haifa",
      "urlName":"maccabi_haifa",
      "confName":"Intl",
      "divName":""
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Houston",
      "altCityName":"Houston",
      "fullName":"Houston Rockets",
      "tricode":"HOU",
      "teamId":"1610612745",
      "nickname":"Rockets",
      "urlName":"rockets",
      "confName":"West",
      "divName":"Southwest"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Indiana",
      "altCityName":"Indiana",
      "fullName":"Indiana Pacers",
      "tricode":"IND",
      "teamId":"1610612754",
      "nickname":"Pacers",
      "urlName":"pacers",
      "confName":"East",
      "divName":"Central"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"LA",
      "altCityName":"LA Clippers",
      "fullName":"LA Clippers",
      "tricode":"LAC",
      "teamId":"1610612746",
      "nickname":"Clippers",
      "urlName":"clippers",
      "confName":"West",
      "divName":"Pacific"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Los Angeles",
      "altCityName":"Los Angeles Lakers",
      "fullName":"Los Angeles Lakers",
      "tricode":"LAL",
      "teamId":"1610612747",
      "nickname":"Lakers",
      "urlName":"lakers",
      "confName":"West",
      "divName":"Pacific"
   },
   {
      "isNBAFranchise":false,
      "isAllStar":false,
      "city":"Melbourne",
      "altCityName":"Melbourne",
      "fullName":"Melbourne United",
      "tricode":"MEL",
      "teamId":"15016",
      "nickname":"United",
      "urlName":"united",
      "confName":"Intl",
      "divName":""
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Memphis",
      "altCityName":"Memphis",
      "fullName":"Memphis Grizzlies",
      "tricode":"MEM",
      "teamId":"1610612763",
      "nickname":"Grizzlies",
      "urlName":"grizzlies",
      "confName":"West",
      "divName":"Southwest"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Miami",
      "altCityName":"Miami",
      "fullName":"Miami Heat",
      "tricode":"MIA",
      "teamId":"1610612748",
      "nickname":"Heat",
      "urlName":"heat",
      "confName":"East",
      "divName":"Southeast"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Milwaukee",
      "altCityName":"Milwaukee",
      "fullName":"Milwaukee Bucks",
      "tricode":"MIL",
      "teamId":"1610612749",
      "nickname":"Bucks",
      "urlName":"bucks",
      "confName":"East",
      "divName":"Central"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Minnesota",
      "altCityName":"Minnesota",
      "fullName":"Minnesota Timberwolves",
      "tricode":"MIN",
      "teamId":"1610612750",
      "nickname":"Timberwolves",
      "urlName":"timberwolves",
      "confName":"West",
      "divName":"Northwest"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"New Orleans",
      "altCityName":"New Orleans",
      "fullName":"New Orleans Pelicans",
      "tricode":"NOP",
      "teamId":"1610612740",
      "nickname":"Pelicans",
      "urlName":"pelicans",
      "confName":"West",
      "divName":"Southwest"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"New York",
      "altCityName":"New York",
      "fullName":"New York Knicks",
      "tricode":"NYK",
      "teamId":"1610612752",
      "nickname":"Knicks",
      "urlName":"knicks",
      "confName":"East",
      "divName":"Atlantic"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Oklahoma City",
      "altCityName":"Oklahoma City",
      "fullName":"Oklahoma City Thunder",
      "tricode":"OKC",
      "teamId":"1610612760",
      "nickname":"Thunder",
      "urlName":"thunder",
      "confName":"West",
      "divName":"Northwest"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Orlando",
      "altCityName":"Orlando",
      "fullName":"Orlando Magic",
      "tricode":"ORL",
      "teamId":"1610612753",
      "nickname":"Magic",
      "urlName":"magic",
      "confName":"East",
      "divName":"Southeast"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Philadelphia",
      "altCityName":"Philadelphia",
      "fullName":"Philadelphia 76ers",
      "tricode":"PHI",
      "teamId":"1610612755",
      "nickname":"76ers",
      "urlName":"sixers",
      "confName":"East",
      "divName":"Atlantic"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Phoenix",
      "altCityName":"Phoenix",
      "fullName":"Phoenix Suns",
      "tricode":"PHX",
      "teamId":"1610612756",
      "nickname":"Suns",
      "urlName":"suns",
      "confName":"West",
      "divName":"Pacific"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Portland",
      "altCityName":"Portland",
      "fullName":"Portland Trail Blazers",
      "tricode":"POR",
      "teamId":"1610612757",
      "nickname":"Trail Blazers",
      "urlName":"blazers",
      "confName":"West",
      "divName":"Northwest"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Sacramento",
      "altCityName":"Sacramento",
      "fullName":"Sacramento Kings",
      "tricode":"SAC",
      "teamId":"1610612758",
      "nickname":"Kings",
      "urlName":"kings",
      "confName":"West",
      "divName":"Pacific"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"San Antonio",
      "altCityName":"San Antonio",
      "fullName":"San Antonio Spurs",
      "tricode":"SAS",
      "teamId":"1610612759",
      "nickname":"Spurs",
      "urlName":"spurs",
      "confName":"West",
      "divName":"Southwest"
   },
   {
      "isNBAFranchise":false,
      "isAllStar":false,
      "city":"Shanghai",
      "altCityName":"Shanghai",
      "fullName":"Shanghai Sharks",
      "tricode":"SDS",
      "teamId":"12329",
      "nickname":"Shanghai Sharks",
      "urlName":"shanghai_sharks",
      "confName":"Intl",
      "divName":""
   },
   {
      "isNBAFranchise":false,
      "isAllStar":false,
      "city":"Sydney",
      "altCityName":"Sydney",
      "fullName":"Sydney Kings",
      "tricode":"SYD",
      "teamId":"15015",
      "nickname":"Kings",
      "urlName":"kings",
      "confName":"Intl",
      "divName":""
   },
   {
      "isNBAFranchise":false,
      "isAllStar":true,
      "city":"Team",
      "altCityName":"Team",
      "fullName":"Team LeBron",
      "tricode":"LBN",
      "teamId":"1610616833",
      "nickname":"Team LeBron",
      "urlName":"team_lebron",
      "confName":"East",
      "divName":"East"
   },
   {
      "isNBAFranchise":false,
      "isAllStar":true,
      "city":"Team",
      "altCityName":"Team",
      "fullName":"Team Stephen",
      "tricode":"STP",
      "teamId":"1610616834",
      "nickname":"Team Stephen",
      "urlName":"team_stephen",
      "confName":"West",
      "divName":"West"
   },
   {
      "isNBAFranchise":false,
      "isAllStar":true,
      "city":"Team Clippers",
      "altCityName":"Team Clippers",
      "fullName":"Team Clippers Team Clippers",
      "tricode":"CLP",
      "teamId":"1610616840",
      "nickname":"Team Clippers",
      "urlName":"team_clippers",
      "confName":"West",
      "divName":"West"
   },
   {
      "isNBAFranchise":false,
      "isAllStar":true,
      "city":"Team Lakers",
      "altCityName":"Team Lakers",
      "fullName":"Team Lakers Team Lakers",
      "tricode":"LKR",
      "teamId":"1610616839",
      "nickname":"Team Lakers",
      "urlName":"team_lakers",
      "confName":"West",
      "divName":"West"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Toronto",
      "altCityName":"Toronto",
      "fullName":"Toronto Raptors",
      "tricode":"TOR",
      "teamId":"1610612761",
      "nickname":"Raptors",
      "urlName":"raptors",
      "confName":"East",
      "divName":"Atlantic"
   },
   {
      "isNBAFranchise":false,
      "isAllStar":true,
      "city":"USA",
      "altCityName":"USA",
      "fullName":"USA",
      "tricode":"USA",
      "teamId":"1610616843",
      "nickname":"USA",
      "urlName":"usa",
      "confName":"East",
      "divName":"East"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Utah",
      "altCityName":"Utah",
      "fullName":"Utah Jazz",
      "tricode":"UTA",
      "teamId":"1610612762",
      "nickname":"Jazz",
      "urlName":"jazz",
      "confName":"West",
      "divName":"Northwest"
   },
   {
      "isNBAFranchise":true,
      "isAllStar":false,
      "city":"Washington",
      "altCityName":"Washington",
      "fullName":"Washington Wizards",
      "tricode":"WAS",
      "teamId":"1610612764",
      "nickname":"Wizards",
      "urlName":"wizards",
      "confName":"East",
      "divName":"Southeast"
   },
   {
      "isNBAFranchise":false,
      "isAllStar":true,
      "city":"World",
      "altCityName":"World",
      "fullName":"World",
      "tricode":"WLD",
      "teamId":"1610616844",
      "nickname":"World",
      "urlName":"world",
      "confName":"East",
      "divName":"East"
   }
];
